version: '3.3'

services:
  local_db:
    image: postgres:alpine
    container_name: local_postgres
    command: postgres -c 'max_connections=50'
    environment:
      TZ: 'Europe/Lisbon'
    ports:
      - 5432:5431
    restart: unless-stopped
    volumes:
      - ./database/dumps/init_pi.sql:/docker-entrypoint-initdb.d/init_pi.sql
    env_file:
      - ./database/local_database.dev.env
    networks:
      local_network:
        ipv4_address: 172.30.0.10
  pi:
    build: ./pi
    image: netmonit-probe
    container_name: probe
    hostname: localhost
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: 'Europe/Lisbon'
    depends_on:
      - local_db
    ports: 
      - 8082
    restart: unless-stopped
    network_mode: host

networks:
  local_network:
    ipam:
      config:
        - subnet: 172.30.0.0/16
